---
#AllCops:
#  DisabledByDefault: true

Layout:
  Enabled: false

Lint:
  Enabled: true

Metrics:
  Enabled: false

Metrics/LineLength:
  Enabled: true
  Max: 130

Naming:
  Enabled: true

Naming/UncommunicativeMethodParamName:
  MinNameLength: 1

Performance:
  Enabled: true

Rails:
  Enabled: false

Security:
  Enabled: true

Style:
  Enabled: false

Style/FormatStringToken:
  Enabled: false

Bundler:
  Enabled: true

Gemspec:
  Enabled: true
