---
#AllCops:
#  DisabledByDefault: true

Layout:
  Enabled: true

Layout/MultilineOperationIndentation:
  EnforcedStyle: indented

Lint:
  Enabled: true

Metrics:
  Severity: refactor
  Enabled: true

Metrics/LineLength:
  Severity: convention
  Max: 130

Naming:
  Enabled: true

Naming/UncommunicativeMethodParamName:
  MinNameLength: 1

Performance:
  Enabled: true

Rails:
  Enabled: false

Security:
  Enabled: true

#todo: enable
Style:
  Enabled: false

Style/FormatStringToken:
  Enabled: false

#todo: enable
Style/StringLiterals:
  Enabled: false

Style/Documentation:
  Enabled: false

Bundler:
  Enabled: true

Gemspec:
  Enabled: true
